pages:
  image: rocker/verse:4.1.0
  before_script:
  - apt-get update && apt-get -y install pandoc r-base
  - R -e "install.packages(c('blogdown'),repos='http://cran.rstudio.com')"
  - R -e "blogdown::install_hugo('0.96.0')"
  script:
    - R -e "blogdown::build_site()"
  artifacts:
    paths:
      - public
  only:
    - master
