baseURL: https://elisemaigne.pages.mia.inra.fr/website/
languageCode: en-us
title: Elise Maigné
theme: hugo-whisper-theme
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
pygmentsUseClasses: yes
module:
  hugoVersion:
    extended: yes
    min: 0.55.0
    summaryLength: 30
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Cours
      url: /cours/
      weight: 2
    - name: Codes
      url: /codes/
      weight: 2
    # - name: Autres
    #   url: /autres/
    #   weight: 4
params:
  custom_css: "css/mycss.css"
  plugins_js: "js/custom.js"
  google_analytics_id: ''
  homepage_button_link: /codes
  homepage_button_text: Des bouts de codes
  homepage_button_link2: /cours
  homepage_button_text2: Des cours/formations/présentations
  homepage_image: /images/RStudio.jpg
  homepage_intro: Ingénieure en statistiques @INRAE (MIAT). R enthusiast. Je fais des trucs en R.
  homepage_meta_tags:
    meta_description: Ingénieure en statistiques @INRAE (MIAT).
    meta_og_description: Ingénieure en statistiques @INRAE (MIAT).
    meta_og_image: https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png
    meta_og_title: Hugo Whisper Theme
    meta_og_type: website
    meta_og_url: https://hugo-whisper.netlify.app
    meta_twitter_card: summary
    meta_twitter_creator: '@zerostaticio'
    meta_twitter_site: '@zerostaticio'
  logo:
    mobile: /images/inrae_logo.png
    standard: /images/inrae_logo.png
  mainSections:
    - codes
    - cours
    # - autres
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: false
