baseURL: https://elisemaigne.pages.mia.inra.fr/rjourney2/
languageCode: en-us
title: Elise Maigné
theme: hugo-whisper-theme
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
pygmentsUseClasses: yes
module:
  hugoVersion:
    extended: yes
    min: 0.55.0
    summaryLength: 30
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Docs
      url: /docs/
      weight: 2
    - name: Codes
      url: /codes/
      weight: 3
    - name: Formations/présentations
      url: /formations/
      weight: 4
params:
  google_analytics_id: ''
  homepage_button_link: /docs
  homepage_button_text: Read The Docs
  homepage_image: /images/RStudio.jpg
  homepage_intro: Ingénieure en statistiques @INRAE (MIAT). R enthusiast. Je fais des trucs en R.
  homepage_meta_tags:
    meta_description: Ingénieure en statistiques @INRAE (MIAT).
    meta_og_description: Ingénieure en statistiques @INRAE (MIAT).
    meta_og_image: https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png
    meta_og_title: Hugo Whisper Theme
    meta_og_type: website
    meta_og_url: https://hugo-whisper.netlify.app
    meta_twitter_card: summary
    meta_twitter_creator: '@zerostaticio'
    meta_twitter_site: '@zerostaticio'
  logo:
    mobile: /images/logo-mobile.svg
    standard: /images/logo.svg
