---
title: benchmark
author: Elise Maigné
date: '2022-04-01'
slug: []
categories:
  - codes
tags:
  - codes
draft: false
summary: Comparer la vitesse de morceaux de codes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Pour comparer la vitesse de 2 bouts de codes (ou plus que 2), on utilise le package rbenchmark.

La structure générale est la suivante : 

```{r, eval=FALSE}
library(rbenchmark)

benchmark(replications=100,
          code1,
          code2,
          columns=c('test', 'elapsed', 'replications'))

```

Et avec un exemple :

```{r}
library(rbenchmark)
library(data.table)

# Ecriture d'un fichier de 15000 lignes 
data(iris)
iris <- iris[rep(rownames(iris), each=100),]
fwrite(iris, file="irisbig.csv", sep=",")

# Lecture du fichier, répétée 1000 fois. 
benchmark(replications=1000,
          read.csv("irisbig.csv", sep=","),
          fread("irisbig.csv"),
          columns=c('test', 'elapsed', 'replications'))
```

Le test2, utilisant la fonction `fread` du package `data.table` est bien plus rapide. 

De la même manière on peut utiliser le package microbenchmark qui a l'avantage d'avoir une belle visualisation avec ggplot2 :

```{r}
library(microbenchmark)
library(ggplot2)

# Lecture du fichier, répétée 1000 fois. 
mb <- microbenchmark(
          read.csv("irisbig.csv", sep=","),
          fread("irisbig.csv"),
          times=1000)

mb
autoplot(mb)
```
